{% set name = "perl-memoize" %}
{% set version = "1.15" %}
{% set sha256 = "070d730c2800e30a291713ee6563bd890d33f36a49458af3f12adc05744416ab" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/A/AR/ARISTOTLE/Memoize-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0
  script:
    - perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
    - make
    - make test
    - make install VERBINST=1

requirements:
  build:
    - make
  host:
    - perl
    - perl-extutils-makemaker
  run:
    - perl
    - perl-extutils-makemaker

test:
  # Perl 'use' tests
  imports:
    - Memoize

about:
  home: https://metacpan.org/pod/Memoize
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_family: OTHER
  summary: Make functions faster by trading space for time
  license_file:
    - {{ environ["PREFIX"] }}/man/man1/perlartistic.1
    - {{ environ["PREFIX"] }}/man/man1/perlgpl.1

extra:
  recipe-maintainers:
    - cbrueffer
